[package]
name = "semver-sort"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
semver = "1.0"
clap = { version = "3.0.10", features = ["derive"] }
