[package]
name = "version"
version = "3.2.0"
edition = "2021"

[[bin]]
name = "semver"
path = "src/main.rs"

[dependencies]
semver = "1.0.9"
clap = { version = "4.5.32", features = ["derive"] }
clap_complete_command = { version = "0.6.1" }

[dev-dependencies]
test-generator = "^0.3"