[package]
name = "version"
version = "2.5.0"
edition = "2021"

[[bin]]
name = "semver"
path = "src/main.rs"

[dependencies]
semver = "1.0.9"
clap = { version = "4.5.23", features = ["derive"] }
clap_complete = { version = "4.5.40" }

[dev-dependencies]
tempfile = "3"